// <auto-generated />
namespace RestAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AuthenticationBeta1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuthenticationBeta1));
        
        string IMigrationMetadata.Id
        {
            get { return "201412011658453_Authentication Beta 1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
